// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

const REMEMBER_KEY = 'huadrink_remember_login';

/** 依「記住登入」設定選用 localStorage 或 sessionStorage（勾選=localStorage 跨關閉保留） */
function getAuthStorage(): Storage {
  try {
    if (typeof window !== 'undefined' && window.localStorage?.getItem(REMEMBER_KEY) === 'false') {
      return window.sessionStorage;
    }
  } catch { /* ignore */ }
  return typeof window !== 'undefined' ? window.localStorage : ({} as Storage);
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.error('[Supabase] 缺少環境變數：請在專案根目錄設定 .env 的 VITE_SUPABASE_URL 與 VITE_SUPABASE_PUBLISHABLE_KEY');
}

// 開發時確認連線目標（前端透過此 client + schema('public') 連到 Supabase）
if (import.meta.env.DEV && SUPABASE_URL) {
  console.info('[Supabase] 前端資料庫連線：', SUPABASE_URL.replace(/^https:\/\//, '').split('.')[0], '| schema: public');
}

/** 單例：避免 React Strict Mode / HMR 重複執行時產生多個 GoTrueClient 實例 */
const SUPABASE_SINGLETON_KEY = '__SUPABASE_CLIENT_HUADRINK__';

function createSupabaseClient() {
  return createClient<Database>(
    SUPABASE_URL || 'https://placeholder.supabase.co',
    SUPABASE_PUBLISHABLE_KEY || 'placeholder-key',
    {
      auth: {
        storage: {
          getItem: (key) => getAuthStorage().getItem(key),
          setItem: (key, value) => getAuthStorage().setItem(key, value),
          removeItem: (key) => getAuthStorage().removeItem(key),
        },
        persistSession: true,
        autoRefreshToken: true,
      },
    }
  );
}

const g = typeof globalThis !== 'undefined' ? (globalThis as Record<string, SupabaseClient<Database> | undefined>) : null;
export const supabase: SupabaseClient<Database> =
  (g && g[SUPABASE_SINGLETON_KEY]) || (g ? (g[SUPABASE_SINGLETON_KEY] = createSupabaseClient()) : createSupabaseClient());

export { REMEMBER_KEY };